import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/FooterSection";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // the weights you want
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className} data-theme="corporate">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
